### ISSUE TITLE
No workflow for lets_encrypt

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE-Deployment#11]
On the main [AzureTRE](https://github.com/microsoft/AzureTRE) repo there is a l[ets_encrypt workflow](https://github.com/microsoft/AzureTRE/blob/main/.github/workflows/lets_encrypt.yml) to create an SSL certificate, that doesn't exist in this repository. Just copying that workflow in fails, as it doesn't execute in the devcontainer.

**Comment by tamirkamara** [comment]
I think it's not the TRE business to provide guidance / procedures on how to obtain a valid HTTPS certificate.
The AzureTRE repo has a workflow for that, but that was built primarily for dev purposes and isn't that stable and might be removed in the future.
At and case, I don't think we'll offer this option here as we don't believe this should be a _deployment_ recommendation.
Obviously you can draw inspiration from the other repo for your own implementation.
