### ISSUE TITLE
Clean Validation Environment workflow fails 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#13]
Running Clean Validation Environment workflow from templated AzureTRE-Deployment, experiencing the following error:

[Clean](https://github.com/daemel/AzureTRE-P2/actions/runs/3092183217/jobs/5003161177#step:3:8)
Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

**Comment by tamirkamara** [comment]
This doesn't include much details to help us understand the issue and since we don't own Azure Login action I'm not sure what to do...

Some things you might want to try:
* Use the credentials to login in a dev machine to validate they are working
* Build a simple workflow to use the credentials and see what happens

**Comment by daemel** [comment]
If the workflow is supplied with a github secret that is undefined

from clean_validation_envs.yml

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  

What should we set the secret Azure Credential to?  In theory I could use the sptrecore identity for rbac with the following setup below, but we have no guidance on this. 

  {
    "clientId": "<GUID>",
    "clientSecret": "<GUID>",
    "subscriptionId": "<GUID>",
    "tenantId": "<GUID>",
  }

**Comment by tamirkamara** [comment]
You got this type of an object in one of the initial setup steps that later you've used for the ARM_* secrets (e.g. ARM_CLIENT_ID).
Can you rebuild the object with those secrets and try again?

**Comment by daemel** [comment]
I am using the ARM secrets as part of the github actions - below are in my Env secrets at this time. 
ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_SUBSCRIPTION_ID
ARM_TENANT_ID

However, the workflow is looking for AZURE_CREDENTIALS, so my question is, should we add that using JSON as above or is another approach preferred?

**Comment by tamirkamara** [comment]
Add another secret per the json example you sent.

**Comment by daemel** [comment]
Doing so will allow login to work, unfortunately the clean ci validation script is not part of the Deployment Repository.  


Log output 
Run devops/scripts/clean_ci_validation_envs.sh
  devops/scripts/clean_ci_validation_envs.sh
  shell: /usr/bin/bash -e ***0***
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    GITHUB_TOKEN: ***
    MAIN_TRE_ID: ***
    BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_STOP: 2
    BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_DESTROY: 48
/home/runner/work/_temp/40f733cb-9622-4df[1](https://github.com/daemel/AzureTRE-P2/actions/runs/3106173851/jobs/5032712941#step:4:1)-bec1-589c79a43466.sh: line 1: devops/scripts/clean_ci_validation_envs.sh: No such file or directory
Error: Process completed with exit code 1[2](https://github.com/daemel/AzureTRE-P2/actions/runs/3106173851/jobs/5032712941#step:4:2)[7](https://github.com/daemel/AzureTRE-P2/actions/runs/3106173851/jobs/5032712941#step:4:7).

**Comment by daemel** [comment]
Tested after latest PR update - same result 

Run devops/scripts/clean_ci_validation_envs.sh
  devops/scripts/clean_ci_validation_envs.sh
  shell: /usr/bin/bash -e ***0***
  env:
    AZURE_HTTP_USER_AGENT: 
    AZUREPS_HOST_ENVIRONMENT: 
    GITHUB_TOKEN: ***
    MAIN_TRE_ID: ***
    BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_STOP: [2](https://github.com/daemel/AzureTRE-P2/actions/runs/3113897988/jobs/5049096569#step:4:2)
    BRANCH_LAST_ACTIVITY_IN_HOURS_FOR_DESTROY: 48
/home/runner/work/_temp/61d7a695-3fa3-4778-a6ae-091a7412e7ea.sh: line 1: devops/scripts/clean_ci_validation_envs.sh: No such file or directory
Error: Process completed with exit code 12[7](https://github.com/daemel/AzureTRE-P2/actions/runs/3113897988/jobs/5049096569#step:4:7).
