### ISSUE TITLE
VM and Private Endpoint failure during Deploy TRE Core 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#14]
I've encountered this error while running Actions -> DeployTRE -> Deploy TRE Core 

module.appgateway.azurerm_monitor_diagnostic_setting.agw: Creating...
module.appgateway.azurerm_monitor_diagnostic_setting.agw: Creation complete after 4s [id=/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.Network/applicationGateways/agw-***|diagnostics-agw-***]
╷
│ Error: waiting for creation of Windows Virtual Machine: (Name "vm-***" / Resource Group "rg-***"): Code="RetryableError" Message="A retryable error occurred."
│ 
│   with azurerm_windows_virtual_machine.jumpbox,
│   on admin-jumpbox.tf line 27, in resource "azurerm_windows_virtual_machine" "jumpbox":
│   27: resource "azurerm_windows_virtual_machine" "jumpbox" {
│ 
╵
╷
│ Error: waiting for creation of Private Endpoint "pe-ampls-***" (Resource Group "rg-***"): Code="InternalServerError" Message="An error occurred." Details=[]
│ 
│   with module.azure_monitor.azurerm_private_endpoint.azure_monitor_private_endpoint,
│   on azure-monitor/azure-monitor.tf line 82, in resource "azurerm_private_endpoint" "azure_monitor_private_endpoint":
│   82: resource "azurerm_private_endpoint" "azure_monitor_private_endpoint" {
│ 
╵
Script done, file is 1663699677-tre-core.log
Terraform Error
make: *** [/home/vscode/AzureTRE/Makefile:103: deploy-core] Error 1
Error: Process completed with exit code 2.

**Comment by daemel** [comment]
On re-running Deploy Core, I now have a TF state issue 

module.azure_monitor.azurerm_log_analytics_linked_storage_account.workspace_storage_customlogs: Creation complete after 9s [id=/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.OperationalInsights/workspaces/log-***/linkedStorageAccounts/customlogs]
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.Compute/virtualMachines/vm-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_windows_virtual_machine" for more information.
│ 
│   with azurerm_windows_virtual_machine.jumpbox,
│   on admin-jumpbox.tf line 27, in resource "azurerm_windows_virtual_machine" "jumpbox":
│   27: resource "azurerm_windows_virtual_machine" "jumpbox" {
│ 
╵
╷
│ Error: A resource with the ID "/subscriptions/***/resourceGroups/rg-***/providers/Microsoft.Network/privateEndpoints/pe-ampls-***" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_private_endpoint" for more information.
│ 
│   with module.azure_monitor.azurerm_private_endpoint.azure_monitor_private_endpoint,
│   on azure-monitor/azure-monitor.tf line 82, in resource "azurerm_private_endpoint" "azure_monitor_private_endpoint":
│   82: resource "azurerm_private_endpoint" "azure_monitor_private_endpoint" {
│ 
╵
Script done, file is 1663706175-tre-core.log
Terraform Error
make: *** [/home/vscode/AzureTRE/Makefile:103: deploy-core] Error 1
Error: Process completed with exit code 2.
##[debug]Finished: run
##[debug]Finishing: Deploy TRE Core

**Comment by tamirkamara** [comment]
Unfortunately cloud deployments sometimes fail. 
The easiest way to get around the issue is to call `make tre-destroy` and then deploy again. A more involved way would be to manually delete the "offending" resource on Azure and then run the deployment again.
Apart from that I don't think we have anything else to offer.
