### ISSUE TITLE
Unable to Register Shared Bundle using GitHub Actions 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#15]
Using GitHub Actions post Deploy main / Deploy TRE 
All Register Shared Bundles start, and all fail at the same place 
As noted previously I have removed ACR_NAME from the Env Secrets as GitHub Actions uses the ACTIONS_ACR_NAME

Example 1 
[Deploy main / Register Shared Bundles (shared_service, \${AZURETRE_HOME}/templates/shared_services/firewall)](https://github.com/daemel/AzureTRE-P2/actions/runs/3099952981/jobs/5020087105#logs)
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Microsoft Azure Sponsorship
»»»   • Tenant:       ***

ERROR: argument --name/-n: expected one argument

Examples from AI knowledge base:
az acr login -n MyRegistry
Log in to an Azure Container Registry

az acr login -n MyRegistry --expose-token
Get an Azure Container Registry access token

https://aka.ms/cli_ref
Read more about the command in reference docs
make: *** [/home/vscode/AzureTRE/Makefile:245: bundle-register] Error 2
Error: Process completed with exit code 2.

Example 2
[Deploy main / Register Shared Bundles (shared_service, \${AZURETRE_HOME}/templates/shared_services/gitea)](https://github.com/daemel/AzureTRE-P2/actions/runs/3099952981/jobs/5020087231#logs)
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Microsoft Azure Sponsorship
»»»   • Tenant:       ***

ERROR: argument --name/-n: expected one argument

Examples from AI knowledge base:
az acr login -n MyRegistry
Log in to an Azure Container Registry

az acr login -n MyRegistry --expose-token
Get an Azure Container Registry access token

https://aka.ms/cli_ref
Read more about the command in reference docs
make: *** [/home/vscode/AzureTRE/Makefile:245: bundle-register] Error 2
Error: Process completed with exit code 2.

**Comment by daemel** [comment]
Any status on this issue?

**Comment by tamirkamara** [comment]
The 0.4.3 release depends on both ACTIONS_ACR_NAME and ACR_NAME which should be different (as I mentioned on another issue). 
The ACTIONS one also needs to be created manually as described [here] (https://github.com/microsoft/AzureTRE/blob/v0.4.3/docs/using-tre/pipelines/index.md). I recognize this document needs work as some of the links got broken.


We are in the process of joining the two ACR so one would only need to provide the desired ACR_NAME without any further steps taken. It will be part of the next release and changes are already visible on the AzureTRE repo.
