### ISSUE TITLE
git and Release Documentation / examples missing 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#19]
Documentation on git updates and Releases would improve the customer functionality of this repo.  For instance there are 2 open pull requests against this repo today, as a customer I have to read in them what changed and then determine to the best of my ability if I need to sync and re-deploy to take advantage of those updates.  The following documentation would help 

Release notes 
With each code update / PR a set of release notes should accompany the PR informing customers of the change and if those changes will affect deployment, operations, etc and if they should be deployed to the customer repo.  If the customers should deploy the changes to their environment then please share code / or a script that should be run to deploy from their template repo to their environment (ensuring that deployment to the environment happens after the changes have been merged from the TRE-Deployment repository - see git Commands below).

git Commands 
If the PR's being released to the TRE-Deployment updates should be replicated to the customers repo, then providing the git commands to add a git remote (the TRE-Deployment repo), create a branch from the TRE-Deployment remote repo and merge changes.

**Comment by martinpeck** [comment]
These are all good suggestions, but this is a template/sample delivered "as is". It's a starting point (and accelerator) and not a product with an upgrade/migration path.

On the docs you mention...

- A full set of release notes is not likely to appear anytime soon, for the reasons above
- I'm not sure what you mean by "git Commands", but I think you're describing some documents that would explain who to use git/how to merge/diff changes. There are online sources of information for this.
