### ISSUE TITLE
Terraform Error in main.tf 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#20]
Following last PR update, issues have been introduced with the main.tf file in AzureTRE repository. 

Log Output 
-------------------------------------
Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.12.0"...
- Using previously-installed hashicorp/azurerm v3.12.0

Terraform has been successfully initialized!
data.azurerm_client_config.current: Reading...
azurerm_resource_group.mgmt: Refreshing state... [id=/subscriptions/***/resourceGroups/***]
data.azurerm_client_config.current: Read complete after 0s [id=2022-09-23 15:40:41.813769401 +0000 UTC]
azurerm_storage_account.state_storage: Refreshing state... [id=/subscriptions/***/resourceGroups/***/providers/Microsoft.Storage/storageAccounts/***]
azurerm_container_registry.shared_acr: Refreshing state... [id=/subscriptions/***/resourceGroups/***/providers/Microsoft.ContainerRegistry/registries/***]
azurerm_storage_container.porter_container: Refreshing state... [id=https://***.blob.core.windows.net/porter]
╷
│ Error: alpha numeric characters only are allowed in "name": ""
│ 
│   with azurerm_container_registry.shared_acr,
│   on main.tf line 43, in resource "azurerm_container_registry" "shared_acr":
│   43:   name                = var.acr_name
│ 
╵
╷
│ Error: "name" cannot be less than 5 characters: ""
│ 
│   with azurerm_container_registry.shared_acr,
│   on main.tf line 43, in resource "azurerm_container_registry" "shared_acr":
│   43:   name                = var.acr_name
│ 
╵
make: *** [/home/vscode/AzureTRE/Makefile:32: mgmt-deploy] Error 1
Error: Process completed with exit code 2.

**Comment by itye-msft** [comment]
Dear @daemel ,
Having a look at the log output, we believe the errors are very descriptive:
`Error: alpha numeric characters only are allowed in "name": "" ` - please make sure the value contains only alpha numeric characters. 
`Error: "name" cannot be less than 5 characters: ""` - please make sure the length of the value is 5 characters or more.

Let us know if the issue persists despite this.
