### ISSUE TITLE
Documentation update for Azure Deployment instructions 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#23]
Would it be possible to have an Azure Deployment section in the Readme.md file.  Today for instance the readme.md contains the following 

Congiguration Setup
The configuration files are required for the AzureTRE local deployment. Before setting up the configuration files make sure to follow the [AzureTRE predeployment steps](https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/pre-deployment-steps/) to setup and understand the required configuration.

It would help to have a section dedicated to Azure deployment rather than local deployment, ie something that points to https://microsoft.github.io/AzureTRE/using-tre/pipelines/pipelines/ along with a dedicated section for an Azure focused installation

**Comment by chboudry** [comment]
here is my own current cheat sheet for CICD installation: 

	1. FORK https://github.com/microsoft/AzureTRE-Deployment 
	2. Open it in Visual studio Code - run container 
	3. Fill in /templates/core/.env and /devops/.env following TRE documentation  https://microsoft.github.io/AzureTRE/tre-admins/setup-instructions/pre-deployment-steps/ and https://microsoft.github.io/AzureTRE/tre-admins/auth/##create_authentication_assets
	4. Run make auth
	5. Create a service principal for github :  az ad sp create-for-rbac --name "RandomAppName"--role owner --scopes /subscriptions/SUBSCRIPTIONID --sdk-auth
	6. Download Github Cli https://github.com/cli/cli/releases
	7. Fill in and run the following Powershell script
$repo = "you forked repo"
$env = "githubenv"
$Secrets = @{
TRE_ID = "";
AAD_TENANT_ID ="";
LOCATION = "";
AUTO_WORKSPACE_APP_REGISTRATION="";
AUTO_WORKSPACE_GROUP_CREATION="";
CORE_ADDRESS_SPACE="";
TRE_ADDRESS_SPACE="";
MGMT_RESOURCE_GROUP_NAME="";
MGMT_STORAGE_ACCOUNT_NAME="";
TERRAFORM_STATE_CONTAINER_NAME="";
ACR_NAME = "";
APPLICATION_ADMIN_CLIENT_ID="";
APPLICATION_ADMIN_CLIENT_SECRET="";
TEST_ACCOUNT_CLIENT_ID="";
TEST_ACCOUNT_CLIENT_SECRET="";
API_CLIENT_ID="";
API_CLIENT_SECRET="";
SWAGGER_UI_CLIENT_ID=""
CORE_APP_SERVICE_PLAN_SKU=""
WORKSPACE_APP_SERVICE_PLAN_SKU=""
AZURE_CREDENTIALS="";
}
$Secrets.keys |  ForEach-Object{ gh secret set $_  -b $Secrets[$_] --repo $repo  --env $env}

Note1 : you might struggle with AZURE_CREDENTAILS multiline secret, you may add this one manually. 
https://learn.microsoft.com/en-us/azure/developer/github/github-key-vault#define-a-service-principal

Note2 : you might want to double check the expected the env variables within the workflow to make sure there aren't new ones
If you forgot one, the process will fail in the middle https://github.com/microsoft/AzureTRE-Deployment/issues/31

	8. Consider removing the cron schedule from the deploy_tre.yml (this is more for dev purposes and a user should only redeploy for a new release)
	9. Run Github Action "Deploy Azure TRE"
	10. You may have to rerun some steps that fails due to timeout at first try :
		a. Keyvault TLS certificate creation
		b. ACR pulling

**Comment by tamirkamara** [comment]
Recent documentation updates made deployment simpler and cleared.
