### ISSUE TITLE
make bootstrap errors or on initial setup 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#24]
Testing Deployment Repo

Certain make commands are necessary to initialize azure before the github actions will work

make bootstrap produces the following Terraform error 

note:   Tenant and Subscription ID's removed for privacy 

@daemel ➜ /workspaces/AzureTRE-P3 (main) $ make bootstrap

»»» 🧩  Bootstrap Terraform...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

Loading local environment variables...
»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Microsoft Azure Sponsorship
»»»   • Tenant:       ***

»»» 🤖 Creating resource group and storage account...
Location        Name
--------------  -------------
northcentralus  oss-mgmt36-rg
AccessTier    AllowBlobPublicAccess    CreationTime                      EnableHttpsTrafficOnly    Kind       Location        MinimumTlsVersion    Name       PrimaryLocation    ProvisioningState    ResourceGroup    StatusOfPrimary
------------  -----------------------  --------------------------------  ------------------------  ---------  --------------  -------------------  ---------  -----------------  -------------------  ---------------  -----------------
Hot           True                     2022-09-28T15:47:03.514915+00:00  True                      StorageV2  northcentralus  TLS1_0               tremgmt36  northcentralus     Succeeded            oss-mgmt36-rg    available
Created
---------
True
Created
---------
True

»»» ✨ Terraform init...

Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.12.0"...
- Installing hashicorp/azurerm v3.12.0...
- Installed hashicorp/azurerm v3.12.0 (signed by HashiCorp)

Terraform has been successfully initialized!

»»» 📤 Importing resources to state...
No instance found for the given address!

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.

~~
/subscriptions/***/resourceGroups/oss-mgmt36-rg
azurerm_resource_group.mgmt: Importing from ID "/subscriptions/***/resourceGroups/oss-mgmt36-rg"...
azurerm_resource_group.mgmt: Import prepared!
  Prepared azurerm_resource_group for import
azurerm_resource_group.mgmt: Refreshing state... [id=/subscriptions/***/resourceGroups/oss-mgmt36-rg]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

No instance found for the given address!

This command requires that the address references one specific instance.
To view the available instances, use "terraform state list". Please modify 
the address to reference a specific instance.
azurerm_storage_account.state_storage: Importing from ID "/subscriptions/***/resourceGroups/oss-mgmt36-rg/providers/Microsoft.Storage/storageAccounts/tremgmt36"...
azurerm_storage_account.state_storage: Import prepared!
  Prepared azurerm_storage_account for import
azurerm_storage_account.state_storage: Refreshing state... [id=/subscriptions/***/resourceGroups/oss-mgmt36-rg/providers/Microsoft.Storage/storageAccounts/tremgmt36]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

State imported
@daemel ➜ /workspaces/AzureTRE-P3 (main) $

**Comment by tamirkamara** [comment]
I believe this error is a result of incorrect environment settings (and/or secrets in Github Actions). Recent documentation updates made the setup processes clearer and this shouldn't happen if you follow the newer versions.
