### ISSUE TITLE
bootstrap.sh Issues / Problems when using GitHub Actions 

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#25]
Two issues occur when running thought GitHub actions.  

1st Issue - can be resolved by adding ARM_TENANT_ID  to the GitHub Env variables.
2nd Issue - can be resolve by adding the following to Env Secrets 

MGMT_RESOURCE_GROUP = Management Reource Group Name 
STATE_STORAGE_ACCOUNT_NAME = Storage Account Name 
TF_STATE_CONTAINER = tfstate (container name) 
TRE_ADDRESS_SPACE: ${{ secrets.TRE_ADDRESS_SPACE }}

Testing:
- Running bootstrap locally does work
- Running bootstrap from the DevContainer (AzureTRE) will also work.  
- Running bootstrap via GitHub Actions will fail 

Process 

Start with the TRE Pipelines page 
https://microsoft.github.io/AzureTRE/using-tre/pipelines/pipelines/

Create Environment (github settings) 
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment

The following environment variables should be defined in your github environment:

Auth env vars - https://microsoft.github.io/AzureTRE/tre-admins/auth/##create_authentication_assets

Added to both GitHub Secrets and to templates/core/.env 

TRE_ID = 
AAD_TENANT_ID =
LOCATION =
AUTO_WORKSPACE_APP_REGISTRATION = true	 
AUTO_WORKSPACE_GROUP_CREATION = false

Core and Devops env vars - https://microsoft.github.io/AzureTRE/tre-admins/environment-variables/

Added to both GitHub Secrets and to devops/.env 

LOCATION = 
MGMT_RESOURCE_GROUP_NAME = 
MGMT_STORAGE_ACCOUNT_NAME = 	
TERRAFORM_STATE_CONTAINER_NAME = 	
ACR_NAME = 

Start Codespaces from Repo / main 

Login to Azure 
az login --tenant <TENANT_ID> --use-device-code (uses MFA)

Run make bootstrap - everything is ok.

Run make bootstrap via GitHub Actions and script fails multiple ways.

1st Problem:  docs are missing a reference to ARM_TENANT_ID that needs to be set in GitHub Secrets 
Error:  
Run docker run --rm --mount \
  

»»» 🧩  Bootstrap Terraform...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...
ERROR: usage error: --service-principal --username NAME -*** --tenant TENANT
ERROR: The subscription of '***' doesn't exist in cloud 'AzureCloud'.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.
ERROR: Please run 'az login' to setup account.

»»» ⚠️ You are not logged in to Azure!
make: *** [/home/vscode/AzureTRE/Makefile:27: bootstrap] Error 1
Error: Process completed with exit code 2.

2nd Problem:    

»»» 🧩  Bootstrap Terraform...

╔══════════════════════════════════════╗
║          Azure TRE Makefile          ║
╚══════════════════════════════════════╝

»»» ✅ Checking pre-reqs...

Checking for Azure CLI...

»»» 🔨 Azure details from logged on user 
»»»   • Subscription: Microsoft Azure Sponsorship
»»»   • Tenant:       ***

»»» 🤖 Creating resource group and storage account...
ERROR: (None) No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/***/resourcegroups/?api-version=2021-04-01'.
Code: None
Message: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/***/resourcegroups/?api-version=2021-04-01'.
make: *** [/home/vscode/AzureTRE/Makefile:27: bootstrap] Error 3
Error: Process completed with exit code 2.

~~

**Comment by tamirkamara** [comment]
I believe this error is a result of incorrect environment settings (and/or secrets in Github Actions). Recent documentation updates made the setup processes clearer and this shouldn't happen if you follow the newer versions.
