### ISSUE TITLE
Update to 0.5.0 release of AzureTRE

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/AzureTRE-Deployment#28]
We need to update this repo to the 0.5.0 release of AzureTRE

It looks like this is started here: https://github.com/microsoft/AzureTRE-Deployment/pull/27

**Comment by marrobi** [comment]
Slightly confused as we also have branch `azuretre-v0.5.0` which has #27 plus additional changes. I pushed some changes there thinking that was the branch that matched the PR.

@stuartleeks should a PR from `azuretre-v0.5.0` replace #27?

cc @tamirkamara @LizaShak

**Comment by marrobi** [comment]
After fixing a couple of issues in  `azuretre-v0.5.0` I get

```
 "status_code": 409,
  "body": ""
```

When installing the firewall. I'm going to try with #27 prior to the CLI shared service steps being added.

**Comment by marrobi** [comment]
Still no luck, as `v0.5.0` makefile relies on the CLI #27 doesn't work either. Suggest we either:
1. Remove the CLI dependency and create a v0.5.1
2. The CLI work is included and the 409 bug above is fixed.
