### ISSUE TITLE
Unable to delete workspaces/resources/services

### ISSUE THREAD

**Issue by MoIocSidi** [microsoft/AzureTRE-Deployment#34]
Error: error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Server 2019 Data Science VM -var image_gallery_id= -var parent_service_id=xxxxxxxxxxxxx -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var

**Comment by marrobi** [comment]
@MoIocSidi can you provide the full error message please, this can be found in the operation log. Thanks.

**Comment by MoIocSidi** [comment]
@marrobi 

: deleting_failed
Action
: uninstall
Message
: 70d71692-0091-4b12-8aa2-61ad7a07612d: Error context message =  [31m╷ [0m [0m  [31m│ [0m  [0m [1m [31mError:  [0m [0m [1mError: Resource Group "rg-cktre01-ws-697b" was not found [0m  [31m│ [0m  [0m  [31m│ [0m  [0m [0m with data.azurerm_resource_group.ws,  [31m│ [0m  [0m on data.tf line 1, in data "azurerm_resource_group" "ws":  [31m│ [0m  [0m 1: data "azurerm_resource_group" "ws"  [4m{ [0m [0m  [31m│ [0m  [0m  [31m╵ [0m [0m error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Server 2019 Data Science VM -var image_gallery_id= -var parent_service_id=72af4416-d58f-46f7-xxxxxxxxxxxxx -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=cxxxx -var tre_resource_id=70d71692-0091xxxxxxxxxxxxxxxx -var vm_size=2 CPU | 8GB RAM -var workspace_id=e40af647-c36e-44a2xxxxxxxxxxxxxxxxxxx: exit status 1 Error: error running command /cnab/app/terraform /usr/bin/terraform destroy -auto-approve -input=false -var image=Server 2019 Data Science VM -var image_gallery_id= -var parent_service_id=72af4416-d58f-46f7-a85b-xxxxxxxxxxxxxx -var shared_storage_access=true -var shared_storage_name=vm-shared-storage -var tre_id=cktre01 -var tre_resource_id=70d71692-0091-4b12-8aaxxxxxxxxxxxxxxxxx -var vm_size=2 CPU | 8GB RAM -var workspace_id=e40af647-c3xxxxxxxxxxxxxxxxx: exit status 1 Error: mixin execution failed: exit status 1 Error: 1 error occurred: * container exit code: 1, message: <nil> az login --identity -u 88422257-e5dc-4721-xxxxxxxxxxxxxxxxx && az acr login --name treacr && porter uninstall "70d71692-0091-4b12-xxxxxxxxxxxxxx" --reference treacr.azurecr.io/tre-service-guacamole-windowsvm:v0.5.2 --param arm_use_msi="true" --param id="70d71692-0091-4xxxxxxxxxxxxxx" --param os_image="Server 2019 Data Science VM" --param parent_service_id="72af4416-d5xxxxxxxxxxxxxxx" --param shared_storage_access="True" --param tfstate_container_name="tfstate" --param tfstate_resource_group_name="tre_mgmt" --param tfstate_storage_account_name="tremgmtstorage" --param tre_id="xxxxx" --param vm_size="2 CPU | 8GB RAM" --param workspace_id="e40af647-c36exxxxxxxxxxxxxxxx" --allow-docker-host-access --force --cred ./vmss_porter/arm_auth_local_debugging.json --cred ./vmss_porter/aad_auth.json

**Comment by marrobi** [comment]
Does the resource group exist/have you manually deleted the resource group `rg-cktre01-ws-697b` via the Azure portal, CLI etc?

If so you will need to clean up the resource documents associated with the workspace and it's services directly in the Cosmos DB.

**Comment by MoIocSidi** [comment]
@marrobi I have not manually deleted the RG

**Comment by marrobi** [comment]
The error says:

`Resource Group "rg-cktre01-ws-697b" was not found `

Can you check that this resource group exists with the exact name. If it does can you take a screenshot of the resource group and paste here as this does not make sense.

Thanks.

**Comment by MoIocSidi** [comment]
My apologies, it wasn't there, however this was never deleted manually, I recreated the RG and tried the delete again. the error now states a virtual network vnet-cktre01-ws-697b doesnt exist.

**Comment by MoIocSidi** [comment]
I have given myself access, I will delete it manually, Thanks

**Comment by marrobi** [comment]
Thanks, if you can work out how the resource group got deleted, let us know.

**Comment by MoIocSidi** [comment]
@marrobi  looking back at events I think the clean environment variable workflow ran and may have caused this
