### ISSUE TITLE
devcontainer build failure

### ISSUE THREAD

**Issue by t-young31** [microsoft/AzureTRE-Deployment#4]
I've tried to build the devcontainer locally and I get the following error

```bash
[276489 ms] Start: Run in container: /bin/sh -c .devcontainer/scripts/post-create-command.sh
find: ‘AzureTRE/devops/’: No such file or directory
[277020 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
```

Just downloading the [AzureTRE release](https://github.com/microsoft/AzureTRE/releases/tag/v0.4.3) seems to fix it.

Hardware: M1 Pro Mac
OS: MacOS 12.5.1
[build_log.txt](https://github.com/microsoft/AzureTRE-Deployment/files/9565721/build_log.txt)

Many thanks for your help in advance.

**Comment by marrobi** [comment]
Thanks @t-young31 just to confirm I have just tested and hit the same issue in WSL.

@tamirkamara @LizaShak is this something you have seen?

**Comment by martinpeck** [comment]
Thanks for the logs. That's useful.

Can you try pulling the latest code, and re-running this again please? A number of files have changed in the repo since this was opened. This issue was opened 7 days ago, but the release of AzureTRE that you're installing appears to be...

```
OSS_VERSION=v0.4.3
```

... and this was only referenced in this deployment repo 3 days ago. So, I'm hoping that pulling the latest code from here and re-running (rebuilding the dev container) will help fix this. 

You shouldn't need to download a copy of the AzureTRE yourself. You should find a download in the location pointed to by...

```
ENV AZURETRE_HOME=/home/$USERNAME/AzureTRE
```

If this doesn't work, can you tell me what `AZURETRE_HOME` is set to inside the devcontainer?

**Comment by marrobi** [comment]
I'm on v0.4.3 and get the same issue, it's set to: `AZURETRE_HOME=/home/vscode/AzureTRE`. 

For some reason the download step on line 96 of the dockerfile doesn't seem to be creating the files, but don't get an error.

**Comment by martinpeck** [comment]
Just to be sure I'm clear: have you...

- pulled the latest version of this repo
- performed a "rebuild dev container" in VS Code

If/when you do, can you share the logs for that please?

**Comment by martinpeck** [comment]
`RUN` layers aren't automatically invalidated, and so I was wondering if we're seeing a cache issue

**Comment by t-young31** [comment]
> Just to be sure what you're done: have you...

pulled the latest version of this repo
performed a "rebuild dev container" in VS Code
If/when you do, can you share the logs for that please?

Just run exactly that & same issue: 
[build_log_22092022.txt](https://github.com/microsoft/AzureTRE-Deployment/files/9627489/build_log_22092022.txt)

**Comment by marrobi** [comment]
I rebuilt without cache and got the same.@martinpeck can you build the dev container from this repo with any success?

**Comment by martinpeck** [comment]
So, I see the same error.
The copy isn't failing. The AzureTRE has been downloaded, and unzipped, exactly where we expect it to be.

For example, I have a folder `/home/vscode/AzureTRE` that contains everything I'd expect, and includes the `version.txt` file that `install-azure-tre-oss.sh` creates as its final step.

So, the Docker commands appear to be working as expected. The `find` is failing in the postCreateCommand step.

**Comment by martinpeck** [comment]
I've got a fix. This certainly allows the devcontainer to build/open successfully, and appears to copy the .env files.

However, it results in git seeing changes because these `.env` files are tracked already.

**Comment by martinpeck** [comment]
@t-young31 hopefully this fixes things for you
