### ISSUE TITLE
Error: unable to pull bundle before installation\uninstall\upgrade

### ISSUE THREAD

**Issue by pselmani** [microsoft/AzureTRE-Deployment#55]
Hi, 

Can anyone help. I have ran the 'make bundle-build\publish\register' on a workspace_service bundle. It registered with API. When I clicked on it to create a new Workspace Service I get the below error

Resource Id
: 583446c7-5081-44ba-8b20-22bd0b32fabd
Resource Path
: /workspaces/a3384f46-c377-44d8-95f8-de5d5d01a7c7/workspace-services/583446c7-5081-44ba-8b20-22bd0b32fabd
Resource Version
: 0
Status
: deployment_failed
Action
: install
Message
: 583446c7-5081-44ba-8b20-22bd0b32fabd: Error context message = Error: unable to pull bundle before installation: unable to pull bundle trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1: error reading porter.yaml for trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1: error unmarshaling custom action schemaVersion: yaml: unmarshal errors: line 1: cannot unmarshal !!str `1.0.0` into manifest.Steps az login --identity -u 7500626c-b78a-49c5-bd19-2e9a47807d08 && az acr login --name trect07acr && porter install "583446c7-5081-44ba-8b20-22bd0b32fabd" --reference trect07acr.azurecr.io/tre-workspace-service-psstorage:v0.1.1 --allow-docker-host-access --force --cred ./vmss_porter/arm_auth_local_debugging.json --cred ./vmss_porter/aad_auth.json

my Porter.yaml looks like this

schemaVersion: 1.0.0
name: tre-workspace-service-psstorage
version: 0.1.1
description: "A storage account workspace service"
dockerfile: Dockerfile.tmpl
registry: azuretre

**Comment by marrobi** [comment]
I believe this error appears when using an old version (< v1) of Porter.

Can you try rebuilding your dev container and reporting back.

**Comment by pselmani** [comment]
I assume version is 1.0.4, if not, where would I check ?

![image](https://user-images.githubusercontent.com/68639496/219506415-9a13cfc6-5bf7-4056-ae24-cad556ac822c.png)

**Comment by marrobi** [comment]
https://porter.sh/cli/porter_version/

If its not the version in the dev container Dockerfile you need to rebuild the dev container via the command palette on VS Code.

**Comment by pselmani** [comment]
The screenshot above is from Dockerfile, below to confirm. So I guess my version is OK so issue must be something else

(main) $ porter version 
porter v1.0.4 (e3a2a5ef)

**Comment by pselmani** [comment]
Is it an issue if Dockerfile has both Porter versions in the code

![image](https://user-images.githubusercontent.com/68639496/219693979-6620b80d-f6c5-4f9c-914b-c932abc1d08b.png)

**Comment by marrobi** [comment]
Hmm, do you have something in your bundle Dockerfile? Pretty sure this is a Porter version issue. 

@tamirkamara any ideas?

**Comment by tamirkamara** [comment]
The original error seem to be copied from the UI/API. Are you sure your deployed system is updated to the same version you're working with in your devcontainer?

**Comment by pselmani** [comment]
The error is taken from UI but same appears on logs of Resource Processor also

How do I check version of resource processor? (I think it's 1.7) I believe the deployed system is below 1.7.
Also, is there a compatibility matrix or does everything need to match all the time. I.e. if we were to upgrade to 1.9, does devcontainer need upgrading also ?

**Comment by tamirkamara** [comment]
When upgrading to a new release of the TRE Solution you should upgrade all core components from devcontainer to all the underlining apps. The easiest way to do this is via a CICD or `make all`.

1.7 doesn't make sense to me :-)
Since you mentioned the Resource Processor logs - look at the application insights logs in your TRE resource group (the "core" one and not any workspace). An example query
```
traces
| where cloud_RoleName == "resource_processor"
| summarize count() by application_Version
```
The minimum version you should be using is `0.5.1`

**Comment by pselmani** [comment]
I mean to say 0.7 but anyway, I ran query on application insights, got below, I guess it's time to upgrade to 0.9 :)

![image](https://user-images.githubusercontent.com/68639496/219970880-a276c5ea-ded2-4b0a-a3ee-d94434fdc157.png)

**Comment by pselmani** [comment]
@tamirkamara if the TRE Solution is older version than devcontainer, what is the recommended route to upgrade the TRE Solution?

**Comment by marrobi** [comment]
You should be able to run `make all` from the newer dev container. 

Ensure you  review the https://github.com/microsoft/AzureTRE/blob/main/CHANGELOG.md and note any breaking changes/migration steps that are needed.

**Comment by pselmani** [comment]
@marrobi Thank you. I ran `make all` and get below error even though I'm Owner on subscription. Any ideas ? or open a new thread

![image](https://user-images.githubusercontent.com/68639496/220639458-925b7b46-0b03-4841-95d3-8303ee1aa674.png)

**Comment by marrobi** [comment]
Closing as believe resovled.
