### ISSUE TITLE
AzureTre master repository not cloned.

### ISSUE THREAD

**Issue by slawpast** [microsoft/AzureTRE-Deployment#57]
As a developer

When I clone the parent repository (as per guide https://microsoft.github.io/AzureTRE/0.8.0/) to my local machine, AzureTRE repository is not copied in as a subfolder (subrepository)
As a result, MakeFile cannot run

1. Clone AzureTre repository in Visual Studo Code (https://github.com/microsoft/AzureTRE-Deployment)
2. Re-open in a Docker container
1. run "Make auth"

**Comment by slawpast** [comment]
Thanks for looking into that. Please find the logs below:

`[+] Building 134.7s (30/30) FINISHED                                                                                         
 => [internal] load build definition from Dockerfile                                                                    0.0s
 => => transferring dockerfile: 5.47kB                                                                                  0.0s
 => [internal] load .dockerignore                                                                                       0.0s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load metadata for mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bullseye                         0.0s
 => [internal] load build context                                                                                       0.0s
 => => transferring context: 10.78kB                                                                                    0.0s
 => CACHED [ 1/25] FROM mcr.microsoft.com/vscode/devcontainers/python:dev-3.8-bullseye                                  0.0s
 => [ 2/25] COPY .devcontainer/scripts/non-root-user.sh /tmp/                                                           0.0s
 => [ 3/25] RUN bash /tmp/non-root-user.sh "vscode" "1000" "1000"                                                       0.5s
 => [ 4/25] RUN su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install lts/* 2>&1"                    6.5s 
 => [ 5/25] COPY .devcontainer/scripts/terraform.sh /tmp/                                                               0.0s 
 => [ 6/25] RUN bash /tmp/terraform.sh "1.3.6" /usr/bin                                                                 2.4s 
 => [ 7/25] COPY .devcontainer/scripts/docker-client.sh /tmp/                                                           0.0s 
 => [ 8/25] RUN /tmp/docker-client.sh vscode                                                                            0.3s 
 => [ 9/25] RUN apt-get update && apt-get install -y ca-certificates curl gnupg lsb-release --no-install-recommends    21.8s 
 => [10/25] RUN if [ "false" = "true" ]; then     apt-get update && apt-get install -y libaugeas0 --no-install-recomme  0.4s
 => [11/25] COPY .devcontainer/scripts/porter.sh /tmp/                                                                  0.0s
 => [12/25] RUN if [ "false" = "true" ]; then     export PORTER_MIRROR=https://cdn.porter.sh     PORTER_VERSION=v0.38.  0.3s
 => [13/25] COPY .devcontainer/scripts/porter-v1.sh /tmp/                                                               0.0s
 => [14/25] RUN export PORTER_VERSION=v1.0.4     PORTER_TERRAFORM_MIXIN_VERSION=v1.0.0     PORTER_AZ_MIXIN_VERSION=v1  29.4s
 => [15/25] COPY .devcontainer/scripts/azure-cli.sh /tmp/                                                               0.0s
 => [16/25] RUN export AZURE_CLI_VERSION=2.37.0-1~bullseye     && /tmp/azure-cli.sh                                    30.0s
 => [17/25] RUN curl -L --fail -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linu  2.4s
 => [18/25] RUN npm install -g pajv@1.2.0                                                                              12.3s
 => [19/25] RUN echo "export HISTFILE=$HOME/commandhistory/.bash_history" >> "$HOME/.bashrc"     && echo "export PROMP  0.4s
 => [20/25] COPY ./.devcontainer/scripts/gh.sh /tmp/                                                                    0.0s
 => [21/25] RUN if [ "false" = "true" ]; then /tmp/gh.sh; fi                                                            0.2s
 => [22/25] COPY .devcontainer/scripts/install-azure-tre-oss.sh .devcontainer/devcontainer.json /tmp/                   0.0s
 => [23/25] RUN oss_version_in_json=$(grep -oP '(?<="OSS_VERSION": ")[^"]*' /tmp/devcontainer.json)     && /tmp/instal  2.2s
 => [24/25] WORKDIR //home/vscode/AzureTRE/cli                                                                          0.0s
 => [25/25] RUN make install-cli && echo -e "\n# Set up tre completion\nsource <(_TRE_COMPLETE=bash_source tre)" >> ~  12.2s
 => exporting to image                                                                                                 13.0s
 => => exporting layers                                                                                                12.9s
 => => writing image sha256:e5c6d263a3ef39f8b11c64e0e7e3f37baa8565d65e5fef7355d17d479870ef81      `

**Comment by slawpast** [comment]
It looks like command `docker build -f ./.devcontainer/Dockerfile .` made the repository and fixed the issue. However when using devcontainers in VS code to create containers this typically doesn't pull in AzureTRE repository as expected.

**Comment by marrobi** [comment]
I imagine you had some sort of transient error, maybe downloading the repo. When the dev container builds you can view the logs and see what might be failing.

I'll close this, but feel free to get back in touch if find an issue.
