### ISSUE TITLE
ENABLE_SWAGGER

### ISSUE THREAD

**Issue by chboudry** [microsoft/AzureTRE-Deployment#62]
I installed TRE today with ENABLE_SWAGGER to true
but i still got the error "Swagger is disabled. Set 'ENABLE_SWAGGER' to true in order to access Swagger." on /api/docs

**Comment by yuvalyaron** [comment]
@chboudry 
Could you please check if you have `ENABLE_SWAGGER` as a an app setting in the configuration of your `api` Web App?
If so, what is its value?

**Comment by chboudry** [comment]
It is set to false here

**Comment by chboudry** [comment]
enable_swagger is set to true by default in config.yaml and I did not change it.
I deployed it through CICD and copied this value to a github secret.

**Comment by yuvalyaron** [comment]
@chboudry I will try to reproduce the issue and circle back to you, however please note that due to current workload, I will only be able to allocate time for further investigation in approximately 2 weeks.
