### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by shrasoni** [microsoft/AzureTRE-Deployment#63]
We have deployed TRE, but not able to authenticate API from swagger, getting below error

Auth ErrorError: response status is 401, error: invalid_client, description: AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented. Trace ID: 493d8809-f97d-404a-8b85-4e64fac8ba00 Correlation ID: 93c27642-619f-44b4-8ea9-1a711aa1bc24 Timestamp: 2023-02-27 09:13:07Z

Please suggest solution for above error.

**Comment by marrobi** [comment]
Please try leaving the 'client_secret' box empty as per https://microsoft.github.io/AzureTRE/v0.9.0/tre-developers/api/#authorization

Does that resolve the issue?

**Comment by shrasoni** [comment]
Thank you, it works for us.
