### ISSUE TITLE
We have deployed TRE, but not able to authenticate API from .Net core application

### ISSUE THREAD

**Issue by shrasoni** [microsoft/AzureTRE-Deployment#65]
We have deployed TRE, but not able to authenticate API from .Net core application while,  authenitcation the Api 
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: 'AADSTS500131: Assertion audience does not match the Client app presenting the assertion. The audience in the assertion was Client id  and the expected audience is 'api:// apid or one of the Application Uris of this application with App ID. The downstream client must request a token for the expected audience (the application that made the OBO request) and this application should use that token as the assertion

Please suggest solution for above error.

**Comment by marrobi** [comment]
As this does not relate to any code in our repositories we are unable to offer support.

However the error explains the issue:

> The audience in the assertion was Client id and the expected audience is 'api:// apid or one of the Application Uris of this application with App ID. The downstream client must request a token for the expected audience (the application that made the OBO request) and this application should use that token as the assertion

Looks like the audience you are using does not match the app ID, the ID can be found as follows:

![image](https://user-images.githubusercontent.com/17089773/223665067-640b154d-a292-4f70-8895-1b817ad90548.png)
