### ISSUE TITLE
CICD fails at ACR Login on first attempt

### ISSUE THREAD

**Issue by azuretresussex** [microsoft/AzureTRE-Deployment#73]
Hi,
 
(I appreciate this is a [known](https://github.com/chboudry/articles/blob/master/tre_installation_cheatsheet.md) issue, but I didn't find an Issue on GH for it.)

When deploying a new AzureTRE, the CICD pipeline fails reliably on ACR Login with the error below. A workaround is available by re-running the workflow, but it would be better if the root cause could be fixed.

<img width="769" alt="image" src="https://github.com/microsoft/AzureTRE-Deployment/assets/132447702/2bde6ac7-316b-4f4c-a905-ed0c14ebdddd">

**Comment by tamirkamara** [comment]
Does it happen on a first run with a new TRE_ID?

**Comment by marrobi** [comment]
Closing as nothing heard back. Could be fixed in #74
