### ISSUE TITLE
Upgrade to version 12

### ISSUE THREAD

**Issue by Danny-Cooke-cCK** [microsoft/AzureTRE-Deployment#82]
We are deploying TRE using via a pipeline and using this deployment template as our base. 

The Upgrade instructions for our scenario suggests we update the OSS_VERSION variable in the .devcontainer only ? 
https://microsoft.github.io/AzureTRE/v0.12.0/tre-admins/upgrading-tre/#how-to-upgrade-azuretre-version
But I notice that this template has been updated this morning to reflect version 12 changes / additions. 

My question now then is, what is the upgrade process for this template ? 
We have used the previous versions and added custom templates. 
A simple pull from origin is needed?

**Comment by marrobi** [comment]
Apologies for the delay, the update process for updating this repository via git is detailed at https://microsoft.github.io/AzureTRE/v0.12.0/tre-admins/upgrading-tre/#how-to-upgrade-azuretre-version

It might be just the OSS version has changed, although you should look at any other changes and decide if they fit your deployment scenario.
