### ISSUE TITLE
Deployment Problems with Makefile

### ISSUE THREAD

**Issue by daemel** [microsoft/AzureTRE-Deployment#9]
Receiving the following error during GitHub Action based deployments.

»»» 🤖 Creating resource group and storage account...
ERROR: (None) No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/***/resourcegroups/?api-version=2021-04-01'.
Code: None
Message: No HTTP resource was found that matches the request URI 'https://management.azure.com/subscriptions/***/resourcegroups/?api-version=2021-04-01'.
make: *** [/home/vscode/AzureTRE/Makefile:27: bootstrap] Error 3
Error: Process completed with exit code 2.

Steps to reproduce
1) Use AzureTRE-Deployment as a template 
2) Store Env variables 
3) Manually trigger Deploy TRE workflow

**Comment by tamirkamara** [comment]
@daemel can you provide more details on this issue as it is hard to understand at what stage you saw this?
Also have you tried a rerun of the action and did it get passed the error?

**Comment by marrobi** [comment]
I've seen this before when one of the variables used in `./devops/terraform/bootstrap.sh` - `TF_VAR_mgmt_resource_group_name`, `TF_VAR_mgmt_storage_account_name`, or `TF_VAR_terraform_state_container_name` are not set. 

Maybe we can add some validation steps to the start of the `bootstrap.sh` file.

**Comment by marrobi** [comment]
I've done a quick PR that will hopefully help - https://github.com/microsoft/AzureTRE/pull/2616

I don't believe you can get this change until a new release is created.

**Comment by daemel** [comment]
> I've seen this before when one of the variables used in `./devops/terraform/bootstrap.sh` - `TF_VAR_mgmt_resource_group_name`, `TF_VAR_mgmt_storage_account_name`, or `TF_VAR_terraform_state_container_name` are not set.
> 
> Maybe we can add some validation steps to the start of the `bootstrap.sh` file.

@marrobi - should those values be set to the same name as MGMT_STORAGE_ACCOUNT_NAME?

**Comment by marrobi** [comment]
The workflow sets these here:

https://github.com/microsoft/AzureTRE-Deployment/blob/d409f5ae5cb6095b5d98b00657f12ffadd8087ae/.github/workflows/deploy_tre_reusable.yml#L195-L197

**Comment by tamirkamara** [comment]
Recent updates should have resolved this issue.
