### ISSUE TITLE
Parameterise the Azure TRE OSS repository location to allow easier repointing to fork

### ISSUE THREAD

**Issue by jonnyry** [microsoft/AzureTRE-Deployment#93]
## Description

As an Azure TRE Developer working on a fork of `microsoft/AzureTRE`, I would like to be able more easily customise the Azure TRE code bundle that is downloaded into the AzureTRE-Deployment Dev Container.

While this is already possible by modifying the URL `install-azure-tre-oss.sh`, it would be tidier and simpler if this was parameterised in `devcontainer.json` like the Azure TRE version number already is.

This would allow the repointing of both the Azure TRE repo and version tag at the same time, in the same file, making is easier to point/repoint the deployment repo.

## Acceptance criteria

- [ ] A new `OSS_REPO` argument is present in `devcontainer.json` set to `microsoft/AzureTRE` 
- [ ] By default, the Dev Container continues to pull the Azure TRE source from `microsoft/AzureTRE`
- [ ] When `OSS_REPO` is set to another Azure TRE fork, the Dev Container pulls from this fork
- [ ] `repository.txt` in the root of the AzureTRE folder contains the value of `OSS_REPO`

**Comment by marrobi** [comment]
Can see this would be beneficial for many users working of a fork. Are you able to implement this, if so, will assign the issue :)

Thanks.

**Comment by jonnyry** [comment]
> Can see this would be beneficial for many users working of a fork. Are you able to implement this, if so, will assign the issue :)
> 
> Thanks.

Yes, of course :-)  PR now attached.
